brew "ccat"
brew "diff-so-fancy"
brew "mise"
brew "gh"
brew "xcodes"

cask "font-fira-code"
cask "swiftformat-for-xcode"
cask "alfred"
cask "1password"
cask "charles"
cask "obsidian"
cask "slack"
cask "spotify"
cask "google-chrome"
